CC=g++

CFLAGS=--std=c++17 -Wall -g -c

FLAGS_G++ = -g -O2 -pedantic -std=c++17 -Wall -Wextra -Werror

all: BigInt.cpp lab6.cpp
	g++ $(FLAGS_G++) BigInt.cpp lab6.cpp -o solution

clean:
	rm -rf *.o solution